
# Site settings
title: "Greeley Colorado Auto Spa"
email: "team@variantstudios.com"
description: "Premium Car Detailing, Clear Bra, Tinting, Ceramic Coatings Colorado."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maraschino-cherry.cloudvent.net" # the base hostname & protocol for your site
#timezone: America/Denver - Don't set for CloudCannon...for reasons.
version: "3.1.6" # the version of jekyll

#CloudCannon defaults
uploads_dir: "assets/images"

# Gems for plugins
gems:
  - jekyll-paginate-v2 # Needed to add paginate on Jekyll ver 3+
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).

# Permalinks
permalink: pretty

# Pagination V2 Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'title'
  sort_reverse: false
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'projects'


# Cloudinary
cloudinaryurl: https://res.cloudinary.com/variant-studios/

#Collections
collections:
  posts:
    output: true
    permalink: '/blog/:title/'
  products:
    output: true
    permalink: '/store/:title/'
  projects:
    output: true
    permalink: '/gallery/:title/'
  services:
    output: true
    permalink: '/services/:title/'
  people:
    output: false
  locations:
    output: false
  categories:
    output: true
    permalink: '/blog/:title/'
  tags:
    output: true
    permalink: '/blog/:title/'

defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      title:
      image_path:
      description:
      author:
      category:
      tags:
  -
    scope:
      type: products
    values:
      layout: store-detail
      title:
      image_path:
      description:
      price_range:
      options:
  -
    scope:
      type: projects
    values:
      layout: gallery-detail
      title:
      image_path:
  -
    scope:
      type: services
    values:
      layout: service-detail
      title:
      description:
      header_image_path:
      images_and_videos:
        - title:
          teaser_image_path:
          large_image_path:
          youtube_url:
      pricing:
      service-table:
        - group:
          desc:
          options:
          - option:
            price:


# Snipcart's Public Key
snipcart-key: 'NjMwNzM3ZWYtODA5ZS00NzI3LWFmZjYtNjIyZTIxZTRmOGEwNjM2MjMxMzQ4OTI1OTg2MDg0'

# typekit - Because we all need nice type faces.
typekit: kqz1qdu

# Google Analytics - What site isn't using it?!
google_analytics_tracking_id:

exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]
