
# Site settings
title: "Auto Spa Colorado"
email: "team@variantstudios.com"
description: "Car Detailing, Clear Bra, Tinting &amp; Ceramic Pro Colorado"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maraschino-cherry.cloudvent.net" # the base hostname & protocol for your site
#timezone: America/Denver - Don't set for CloudCannon...for reasons.
version: "3.1.6" # the version of jekyll
author.name: "Variant Studios"
author.email: "team@variantstudios.com"

# Gems for plugins
gems:
  - jekyll-cloudinary
  - jekyll-paginate # Needed to add paginate on Jekyll ver 3+
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).

# Permalinks
permalink: pretty

# Pagination
paginate: 10
paginate_path: '/blog/:num/'

# Cloudinary
cloudinary:
  cloud_name: variant-studios
  api_key: "796987956754394"
  verbose: true
  presets:
      default:
        min_width: 320
        max_width: 1200
        fallback_max_width: 800
        steps: 5
        sizes: "(min-width: 50rem) 50rem, 90vw"
      onethird:
        min_width: 110
        max_width: 535
        fallback_max_width: 300
        steps: 3
        sizes: "(min-width: 50rem) 17rem, 30vw"
        attributes:
          class: "one3rd"

#Collections
collections:
  posts:
    output: true
    permalink: '/blog/:title/'
  products:
    output: true
    permalink: '/store/:title/'
  projects:
    output: true
    permalink: '/gallery/:title/'
  people:
    output: false
  categories:
    output: true
    permalink: '/blog/:title/'
  tags:
    output: true
    permalink: '/blog/:title/'

defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      title:
      image_path:
      description:
      author:
      category:
      tags:
  -
    scope:
      type: products
    values:
      layout: store-detail
      title:
      image_path:
      description:
      price_range:
      options:
  -
    scope:
      type: projects
    values:
      layout: gallery
      title:
      image_path:

# typekit - Because we all need nice type faces.
typekit: kqz1qdu

# Google Analytics - What site isn't using it?!
google_analytics_tracking_id:

exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]
